### ISSUE TITLE
How to route other containers through this for VPN?

### ISSUE THREAD

**Issue by Ltek** [wiorca/docker-windscribe-mono#2]
I've been doing a ton of reading but cant find this exact answer. I have Deluge and Jackett containers running from linuxsever's images. 

How can I route those through a container made from your image? 

1. Looks like I need to add --net=container:<VPNs CONTAINER NAME> to the other images?
2. Is there a way to add that without rebuilding those containers (and needing to redo those app settings/configurations)?
3. Do I need to add the ports to your container?  -p 8112:8112  -p 9117:9117

thx for helping a noob

**Comment by wiorca** [comment]
Hey,

This is less of a image issue, and more of a configuration issue, but here's my take on it:

- This image contains mono.  I don't think you need that for this use case.  Just use wiorca/docker-windscribe image instead.
- - You should not forward any ports for this container.  They are not needed.  Only the VPN connection and connection from the local docker images should be permitted.  Otherwise you're potentially exposing yourself and bypassing the VPN.
- --net=container is not something I've tested, but it should work with the wiorca/docker-windscribe image.  You should not need to do anything to the other containers, as the configuration should not be stored in the running container.  It should be stores elsewhere.  Use docker-compose to make re-starting, re-creating, and reconfiguring images easier.  


Good luck!
